#input grid on which superobbing is performed
grid:
  filename: grids/soca_gridspec.nc #soca_gridspec.025deg.nc
  lat: lat   # The variable in the file holding latitude
  lon: lon   # The variable in the file holding longitude
binning:
  mode: superob  # type of binning.
                 # Currently only "superob" is supported
                 #   errors:
  errors:
    # output observation errors are calculated as follow:
    #     #
    #         # ObsError = base + error_mean_mult * mean(ObsError)
    #             #                 + value_stddev_mult * stddev(ObsValue)
    #                 #
    #                     # E.g. the following defaults will add the standard
    #                         # deviation of the binned obs values as a component of the
    #                             # observation error, to account for grid representativeness error.
    base: 0.0
    error mean mult: 1.0
    value stddev mult: 1.0
obs input file: /work/noaa/ng-godas/spaturi/nggodas_realtime_ext/ng-godas/obs/ioda-v2/ostia/2019/20190914/sst_ostia_20190914.nc 
obs output file: /work/noaa/ng-godas/spaturi/nggodas_realtime_ext/ng-godas/obs/ioda-v2/ostia/superob/2019/20190914/sst_ostia_20190914.nc 
