#!/bin/ksh
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_DA_LETKF
# Run UMD-LETKF (Recenter and Remapping)
#================================================================================
#================================================================================
EOF

module purge
source $MOD_PATH/godas.main
module list

echo
echo "The system runs at $RUNCDATE"
echo
echo "The LETKF directory is " ${LETKFDIR}

cd ${LETKFDIR}

cat <<EOF
#============================================
# Run UMD-LETKF
#============================================
EOF

if [ -f "${LETKFDIR}/soca_gridspec.nc" ]; then
    echo
    echo 'SOCA grid exist, by-passing grid generation.'
    echo
else
    echo
    echo 'No grid found. Generating SOCA grid.'
    echo
    srun -n $NPE ${SOCA_EXEC}/soca_gridgen.x ${LETKFDIR}/yaml/gridgen.yml
fi

if [ -f "${ROOT_GODAS_DIR}/build/letkf/bin/letkfdriver" ]; then
 
    srun -n $NPE ${ROOT_GODAS_DIR}/build/letkf/bin/letkfdriver ${LETKFDIR}/yaml/letkf.yaml

else
    echo
    echo 'letkfdriver does not exist.'
    echo
fi

#cat <<EOF
##============================================
## Run Recenter
##============================================
#EOF

#srun -n $NPE ${SOCA_EXEC}/soca_ensrecenter.x ./yaml/ensrecenter.yml
