#!/bin/bash -l
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_FORECAST
#   Run the forecast and then run the post_forecast script to copy over output
#================================================================================
#================================================================================
EOF

case $FCSTMODEL in
   "MOM6solo")
      module purge
      source $MOD_PATH/godas.main
      module list

      cd $RUNCDATE
      export OOPS_TRACE=0

      #============================================
      # Run mom6 only forecast
      #============================================
      if   [ ! -d RESTART ]; then mkdir -p RESTART; fi
      srun -n $NPE ${SOCA_EXEC}/soca_forecast.x ./yaml/forecast.yml

      #============================================
      # Move ocean and ice restarts to place holder for next cycle
      #============================================
      mv ./RESTART ../NEXT_IC
      mv ./ANA/cice_bkg.nc ../NEXT_IC/ # Percistance for sea-ice
      ;;
   "MOM6CICE5")
      module purge
      source $MOD_PATH/godas.fcst
      module list
      
      #TODO: This should be a configuration calculation/currently defined in multiple places
      #for now all these values should be hardcoded, these are things that should be controld
      #by global-workflow forecast anyways
      ##ATMPETS=${ATMPETS:-"72"}   #Number of ATM Pets
      ##OCNPETS=${OCNPETS:-"120"}  #number of ocean pets
      ##ICEPETS=${ICEPETS:-"48"}   #number of ice pets
      ##NTASKS_TOT=${NTASKS_TOT:-"$(( $ATMPETS+$OCNPETS+$ICEPETS ))"} #240

      NPE_FCST=${NTASKS_TOT:-240}

      #TODO: DATA defined multiple places...
      DATA=$RUNCDATE/fcst
      FORECAST_EXE=${ROOT_GODAS_DIR}/src/DATM-MOM6-CICE5.fd/NEMS/exe/nems_datm_mom6_cice5.x

      if [ "$NO_ENS_MBR" -le "1" ];then
         echo "Forecast Run Directory: $DATA"
         echo "Forecast exe: $FORECAST_EXE"
         echo "Number of tasks: $NPE_FCST"
         echo "Run command: srun -n $NPE_FCST ${FORECAST_EXE}"

         cd $DATA
         srun -n $NPE_FCST ${FORECAST_EXE}

          echo "Finished forecast, now copy output using script: ${ROOT_GODAS_DIR}/scripts/post_forecast.sh"
      # Copy ICs for next cycle, copy output to save location, cleanup forecast directory
         ${ROOT_GODAS_DIR}/scripts/post_forecast.sh

      else
      # Get ENSBEG/ENSEND from ENSGRP and NMEM_EFCSGRP
         export ENSEND=$((NMEM_PGRP * ENSGRP))
         export ENSBEG=$((ENSEND - NMEM_PGRP + 1))
         echo ENSGRP $ENSGRP ENSBEG $ENSBEG ENSEND $ENSEND
         for MEMBER_NO in $(seq $ENSBEG $ENSEND); do
            DATAtmp=$DATA"/mem"$MEMBER_NO
            echo Member to be prepared: $MEMBER_NO
            echo "Forecast Run Directory: $DATAtmp"
            echo "Forecast exe: $FORECAST_EXE"
            echo "Number of tasks: $NPE_FCST"
            echo "Run command: srun -n $NPE_FCST ${FORECAST_EXE}"

            cd $DATAtmp
            srun -n $NPE_FCST ${FORECAST_EXE}

            echo "Finished forecast, now copy output using script: ${ROOT_GODAS_DIR}/scripts/post_forecast.sh -n $MEMBER_NO"

      # Copy ICs for next cycle, copy output to save location, cleanup forecast directory
            ${ROOT_GODAS_DIR}/scripts/post_forecast.sh -n $MEMBER_NO

         done
      fi

      echo "End of Forecast for $CDATE"
      ;;
esac
