#!/bin/bash
#set -e

#================================================================================
#================================================================================
# Run SOCA 3DVAR

module purge
module use -a /scratch2/NCEPDEV/marine/marineda/modulefiles/
module load jedi-intel-17.0.5.239

echo $RUNCDATE
cd $RUNCDATE

# Run 3DVAR
export OOPS_TRACE=0
srun -n $NPE ${SOCA_EXEC}/soca_3dvar.x ./yaml/3dvar_godas.yml

# Checkpoint 3DVAR analysi
if   [ ! -d RESTART ]; then mkdir -p RESTART; fi
srun -n $NPE ${SOCA_EXEC}/soca_checkpoint_model.x ./yaml/checkpointmodel.yml

# Prepare restarting from analysis
mv RESTART ANA                 # Because checkpoint dumps analysis in RESTART
ln -s $PWD/INPUT_MOM6/* ./ANA/ # Sym link won't over-write hard copy, so all good
rm $PWD/ANA/cice_bkg.nc 
ln -s $PWD/Data/cic.3dvargodas.an.*.nc ./ANA/cice_bkg.nc

# Run mom6 only forecast
if   [ ! -d RESTART ]; then mkdir -p RESTART; fi
srun -n $NPE ${SOCA_EXEC}/soca_forecast.x ./yaml/forecast.yml

# Move ocean and ice restarts to place holder for next cycle
mv ./RESTART ../NEXT_IC
mv ./ANA/cice_bkg.nc ../NEXT_IC/
