#!/bin/bash
#set -e

#================================================================================
#================================================================================
# Run SOCA 3DVAR

module purge
module use -a /contrib/da/modulefiles
module load jedi/jedim

echo $RUNDIR
cd $RUNDIR

# Run 3DVAR
srun -n 312 ${SOCA_EXEC}/soca_3dvar.x ./yaml/3dvar_godas.yml


