#!/bin/bash
#set -e

#================================================================================
#================================================================================
# Prep SOCA Static B and grid

module purge
module use -a /contrib/da/modulefiles
module load jed/jedim
module listi

echo $RUNDIR

if [ ! -d $RUNDIR ]; then mkdir -p $RUNDIR; fi
cd $RUNDIR

# Generate ocean-ice grid
srun --nodes=1 --ntasks=12 ${SOCA_EXEC}/soca_gridgen.x ./yaml/gridgen.yml

# Create BUMP convolution operator
mkdir -p bump
srun -n 312 ${SOCA_EXEC}/soca_staticbinit.x ./yaml/static_SocaError_init.yml
