#!/bin/ksh
#set -e

#================================================================================
#================================================================================
# Generate the ensemble

. $ROOT_GODAS_DIR/ush/load_godas_modules.sh
status=$?
[[ $status -ne 0 ]] && exit $status\

echo $RUNCDATE

if [ ! -d $RUNCDATE ]; then mkdir -p $RUNCDATE; fi
cd $RUNCDATE

if   [ ! -d RESTART ]; then mkdir -p RESTART; fi

# Generate the ensemble using soca_enspert

srun -n $NPE ${SOCA_EXEC}/soca_enspert.x ./yaml/genenspert.yml 
