#!/bin/ksh
set -e

cat <<EOF
#================================================================================
#============================================
# Run Recenter                                                                                                         
#============================================
#================================================================================
EOF

. $ROOT_GODAS_DIR/ush/load_godas_modules.sh
status=$?
[[ $status -ne 0 ]] && exit $status

echo
echo "The system runs at $RUNCDATE"
echo
echo "The RECENTER LETKF directory is " ${LETKFDIR}

cd ${LETKFDIR}

if [ ! -d RESTART ]; then mkdir -p RESTART; fi

export ENSEND=$((NMEM_PGRP * ENSGRP))
export ENSBEG=$((ENSEND - NMEM_PGRP + 1))

for MEMBER_NO in $(seq $ENSBEG $ENSEND); do
   echo
   echo Running Checkpoint for the $MEMBER_NO

   #Add h 3d field in ana files
   if [ -d /work ] ; then module load nco/4.8.1; fi
   ncap2 -O -s 'h[time,vt1,lat,lon]=0.0' ${LETKFDIR}/ocn.ana.$MEMBER_NO.nc ${LETKFDIR}/ocn.ana.$MEMBER_NO.nc
   ncks -A -C -v h ${LETKFDIR}/Data/ocn.pert.ens.$MEMBER_NO.nc ${LETKFDIR}/ocn.ana.$MEMBER_NO.nc

   cp ${LETKFDIR}/ocn.ana.$MEMBER_NO.nc ${LETKFDIR}/Data/ocn.ana.$MEMBER_NO.nc
   # srun -n $NPE ${SOCA_EXEC}/soca_checkpoint_model.x ./yaml/checkpointmodel$MEMBER_NO.yml
   #TMP fix nan salt value problem caused by soca_pert
   if [ -f "${LETKFDIR}/Data/tmp.nc" ]; then rm ${LETKFDIR}/Data/tmp.nc; fi
   python $ROOT_GODAS_DIR/test/check_nan.py ${LETKFDIR}/Data/ocn.ana.$MEMBER_NO.nc ${LETKFDIR}/Data/tmp.nc
   ncks -A -C -v Salt ${LETKFDIR}/Data/tmp.nc ${LETKFDIR}/Data/ocn.ana.$MEMBER_NO.nc
   #checkpoint
   srun -n $NPE ${SOCA_EXEC}/soca_checkpoint_model.x ./yaml/checkpointmodel$MEMBER_NO.yml

   # TODO: The ice is not pertubated but eventually, it will.
   # ciceprep_func "${RUNCDATE}/Data/cic.pert.ens.*.nc"                   

   mkdir -p ${LETKFDIR}/mem$MEMBER_NO

   mv -f RESTART/* ${LETKFDIR}/mem$MEMBER_NO
done

for MEMBER_NO in $(seq $ENSBEG $ENSEND); do
    mv ${LETKFDIR}/ocn.ana.$MEMBER_NO*.nc ${LETKFDIR}/Data
    ln -s ${LETKFDIR}/mem$MEMBER_NO/MOM.res.nc ocn.ana.$MEMBER_NO.nc 
done
if [ -f "${LETKFDIR}/Data/tmp.nc" ]; then rm ${LETKFDIR}/Data/tmp.nc; fi


srun -n $NPE ${SOCA_EXEC}/soca_ensrecenter.x ./yaml/ensrecenter.yml
