#!/bin/bash
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_DA_LETKF
# Run UMD-LETKF (Recenter and Remapping)
#================================================================================
#================================================================================
EOF

module purge
source $MOD_PATH/godas.main
module list

echo
echo "The system runs at $RUNCDATE"
echo
echo "The LETKF directory is " ${LETKFDIR}

cd ${LETKFDIR}

cat <<EOF
#============================================
# Run UMD-LETKF
#============================================
EOF

srun -n $NPE ${SOCA_EXEC}/letkfdriver ${LETKFDIR}/yaml/letkf.yaml

#cat <<EOF
##============================================
## Run Recenter
##============================================
#EOF

#srun -n $NPE ${SOCA_EXEC}/soca_ensrecenter.x ./yaml/ensrecenter.yml
