#!/bin/bash -l
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_PREP_FORECAST
#   Set up DIRs, make input files, copy over fix files 
#================================================================================
#================================================================================
EOF

case $FCSTMODEL in
   "MOM6solo")
      ;;
   "MOM6CICE5")
      #TODO: DATA defined multiple places... 
      DATA=$RUNCDATE/fcst
      ${ROOT_GODAS_DIR}/scripts/prep_forecast.sh
      ;;
esac
