#!/bin/ksh
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_HOFX
# Run SOCA HOFX
#================================================================================
#================================================================================
EOF

echo ''
echo 'Date of Analysis: ' $CDATE
echo 'Run Directory: ' $RUNCDATE
echo ''

. $ROOT_GODAS_DIR/ush/load_godas_modules.sh
status=$?
[[ $status -ne 0 ]] && exit $status

cd $RUNCDATE

# Get ENSBEG/ENSEND from ENSGRP and NMEM_EFCSGRP


if [ "$NO_ENS_MBR" -le "1" ];then

   srun -n $NPE ${SOCA_EXEC}/soca_hofx_nomodel.x ./yaml/hofx3d.yml

else

   export ENSEND=$((NMEM_PGRP * ENSGRP))
   export ENSBEG=$((ENSEND - NMEM_PGRP + 1))

   HOFXDIR=$RUNCDATE/hofx

   for MEMBER_NO in $(seq $ENSBEG $ENSEND); do

      echo
      echo Preparing the hofx for ensemble member $MEMBER_NO

      cd $HOFXDIR/mem${MEMBER_NO}

      if [ -f "$HOFXDIR/mem${MEMBER_NO}/soca_gridspec.nc" ]; then
	  echo
	  echo 'SOCA grid exist, by-passing grid generation.'
	  echo
      else
	  echo
	  echo 'No grid found. Generating SOCA grid.'
	  echo
	  srun -n $NPE ${SOCA_EXEC}/soca_gridgen.x $HOFXDIR/mem${MEMBER_NO}/yaml/gridgen.yml
      fi

      srun -n $NPE ${SOCA_EXEC}/soca_hofx_nomodel.x $HOFXDIR/mem${MEMBER_NO}/yaml/hofx3d${MEMBER_NO}.yml

   done

fi
