#!/bin/bash -l
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_FORECAST
#   Run the forecast and then run the post_forecast script to copy over output
#================================================================================
#================================================================================
EOF

module purge
source $MOD_PATH/godas.fcst
module list

#TODO: DATA defined multiple places...
DATA=$RUNCDATE/fcst
FORECAST_EXE=${ROOT_GODAS_DIR}/src/DATM-MOM6-CICE5.fd/NEMS/exe/nems_datm_mom6_cice5.x

#TODO: This should be a configuration calculation/currently defined in multiple places 
#for now all these values should be hardcoded, these are things that should be controld 
#by global-workflow forecast anyways
##ATMPETS=${ATMPETS:-"72"}   #Number of ATM Pets
##OCNPETS=${OCNPETS:-"120"}  #number of ocean pets
##ICEPETS=${ICEPETS:-"48"}   #number of ice pets
##NTASKS_TOT=${NTASKS_TOT:-"$(( $ATMPETS+$OCNPETS+$ICEPETS ))"} #240

NPE_FCST=${NTASKS_TOT:-240}


echo "Forecast Run Directory: $DATA" 
echo "Forecast exe: $FORECAST_EXE"
echo "Number of tasks: $NPE_FCST"
echo "Run command: srun -n $NPE_FCST ${FORECAST_EXE}"

cd $DATA
srun -n $NPE_FCST ${FORECAST_EXE}

echo "Finished forecast, now copy output using script: ${ROOT_GODAS_DIR}/scripts/post_forecast.sh"
# Copy ICs for next cycle, copy output to save location, cleanup forecast directory 
${ROOT_GODAS_DIR}/scripts/post_forecast.sh

echo "End of Forecast for $CDATE" 
