#!/bin/bash
#set -e

#================================================================================
#================================================================================
# 

echo ''
echo 'Running the JJOB for PREP_LETKF, aka SOCA HoFx'
echo 'Date of Analysis: ' $CDATE
echo ''

module purge
module use -a /contrib/da/modulefiles
module load jedi

# Change of the coordinates
# TODO

# Run H(x)

srun -n 24 ${SOCA_EXEC}/soca_hofx3d.x ./yaml/hofx3dMEMBER_NO.yml
