#!/bin/ksh
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_LETKF_PREP
#  -Prepare yaml files UMD-LETKF application
#  -Prepare the path structure for the analysis
#================================================================================
#================================================================================
EOF

. $ROOT_GODAS_DIR/ush/load_godas_modules.sh
status=$?
[[ $status -ne 0 ]] && exit $status

# Main 
# ----------------------------------- 

echo
echo "The system runs at $RUNCDATE"
echo
echo "The LETKF directory is " ${LETKFDIR}
echo
echo "SOCA_STATIC="$SOCA_STATIC

mkdir -p ${LETKFDIR}

cd ${LETKFDIR}

sh ${ROOT_GODAS_DIR}/scripts/prep_letkf.sh -n $NO_ENS_MBR
