#!/bin/bash
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_POST_GEN_ENSEMBLE
#   - Checkpoint
#================================================================================
#================================================================================
EOF

module purge
source $MOD_PATH/godas.main
module list

# Functions 
rename_func () { for files in $1; do mv $files ${files:0:(${#files}-28)}'nc'; done }


# Main 
# ----------------------------------- 

echo
echo "The system runs at $RUNCDATE"
echo

cd ${RUNCDATE}/Data

rename_func "cic.pert.ens.*.PT0S.nc"
rename_func "ocn.pert.ens.*.PT0S.nc"

cd ${RUNCDATE}

if [ ! -d RESTART ]; then mkdir -p RESTART; fi

export ENSEND=$((NMEM_PGRP * ENSGRP))
export ENSBEG=$((ENSEND - NMEM_PGRP + 1))

for MEMBER_NO in $(seq $ENSBEG $ENSEND); do
   echo 
   echo Running Checkpoint for the $MEMBER_NO

   srun -n $NPE ${SOCA_EXEC}/soca_checkpoint_model.x ./yaml/checkpointmodel$MEMBER_NO.yml

   mkdir -f ${RUNCDATE}/mem$MEMBER_NO
   mv -rf RESTART/* mem${RUNCDATE}/$MEMBER_NO

done
