#!/bin/bash
#set -e

#================================================================================
#================================================================================
# 

echo ''
echo 'Running the JJOB for PREP_LETKF, aka SOCA HoFx'
echo 'Date of Analysis: ' $CDATE
echo 'Run Directory: ' $RUNCDATE
echo ''

module purge
module use -a /scratch1/NCEPDEV/stmp4/Daniel.Holdaway/opt/modulefiles
module load apps/jedi/intel-19.0.5.281

rename_func () { for files in $1; do cp $files ${files:0:(${#files}-28)}'nc'; done }

# Rename the ensemble members
cd $RUNCDATE/Data

rename_func "cic.pert.ens.*.PT0S.nc"
rename_func "ocn.pert.ens.*.PT0S.nc"

cd $RUNCDATE

# Change of the coordinates
# TODO
rename_func () { for files in $1; do cp $files ${files:0:(${#files}-28)}'nc'; done }

# Rename the ensemble members
cd $RUNCDATE/Data

rename_func "cic.pert.ens.*.PT0S.nc"
rename_func "ocn.pert.ens.*.PT0S.nc"

cd $RUNCDATE
echo $MEMBER_NO
# Run H(x)

srun -n $NPE ${SOCA_EXEC}/soca_hofx3d.x ./yaml/hofx3d$MEMBER_NO.yml
