#!/bin/ksh
set -e

#================================================================================
#================================================================================
# Prep SOCA Static B and grid

. $ROOT_GODAS_DIR/ush/load_godas_modules.sh
status=$?
[[ $status -ne 0 ]] && exit $status

echo $RUNCDATE

if [ ! -d $RUNCDATE ]; then mkdir -p $RUNCDATE; fi
cd $RUNCDATE

# Generate ocean-ice grid
if [ -f "${RUNCDATE}/soca_gridspec.nc" ]; then
    echo
    echo 'SOCA grid exist, by-passing grid generation.'
    echo
else
    echo
    echo 'No grid found. Generating SOCA grid.'
    echo
    srun --nodes=1 --ntasks=12 ${SOCA_EXEC}/soca_gridgen.x ./yaml/gridgen.yml
fi

# Create BUMP convolution operator
echo
echo 'Initializing BUMP.'
echo
mkdir -p bump
srun -n $NPE ${SOCA_EXEC}/soca_staticbinit.x ./yaml/static_SocaError_init.yml
