#!/bin/bash
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_POST
#   Cleanup, archive, plot stuff, ...
#================================================================================
#================================================================================
EOF
# Plot results
source $MOD_PATH/godas.python
${ROOT_GODAS_DIR}/scripts/post_plot.sh

# Remove BUMP files
# TODO: After update to soca, bump only needs to be initialized once
#       per layout.
if [ -d $RUNCDATE/bump ]; then rm -rf $RUNCDATE/bump/; fi

# Remove model dependent peanuts
case $FCSTMODEL in
   "MOM6solo")
       # TODO: Figure out what needs to be cleaned-up
       echo "Not implemented yet"
       ;;
   "MOM6CICE5")
       # TODO: Keep something from fcst?
       if [ -d $RUNCDATE/fcst ]; then rm -rf $RUNCDATE/fcst; fi
       if [ -d $RUNCDATE/test-emc-m6c5 ]; then rm -rf $RUNCDATE/test-emc-m6c5; fi
       ;;
esac
