#!/bin/bash
#set -e

#================================================================================
#================================================================================
# Generate the ensemble

module purge
source $MOD_PATH/godas.main
module list

echo $RUNCDATE

if [ ! -d $RUNCDATE ]; then mkdir -p $RUNCDATE; fi
cd $RUNCDATE

if   [ ! -d RESTART ]; then mkdir -p RESTART; fi

# Generate the ensemble using soca_enspert

srun -n $NPE ${SOCA_EXEC}/soca_enspert.x ./yaml/genenspert.yml 
