#!/bin/bash
#set -e

#================================================================================
#================================================================================
# Run SOCA 3DVAR

module use -a /contrib/da/modulefiles
module load jedi
module load nco

cd $RUNDIR
srun -n 312 $SOCA_EXEC/soca_3dvar.x ./yaml/3dvar_godas.yml


