#!/bin/bash
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_PREP_SOCA
# Prep SOCA Static B and grid
#================================================================================
#================================================================================
EOF

module purge
source $MOD_PATH/godas.main
module list

echo $RUNCDATE

if [ ! -d $RUNCDATE ]; then mkdir -p $RUNCDATE; fi
cd $RUNCDATE

# Generate ocean-ice grid
if [ -f "${RUNCDATE}/soca_gridspec.nc" ]; then
    echo
    echo 'SOCA grid exist, by-passing grid generation.'
    echo
else
    echo
    echo 'No grid found. Generating SOCA grid.'
    echo
    srun -n $NPE ${SOCA_EXEC}/soca_gridgen.x ./yaml/gridgen.yml
fi

# Create BUMP convolution operator (computes convolution weights)
echo
echo 'Initializing BUMP.'
echo
mkdir -p bump
srun -n $NPE ${SOCA_EXEC}/soca_staticbinit.x ./yaml/static_SocaError_init.yml

# Initialize BUMP localization (computes localization weights)
if [ ${NO_ENS_MBR}>1 ]; then
    echo
    echo 'Initializing BUMP Localization.'
    echo
    srun -n $NPE ${SOCA_EXEC}/soca_parameters.x ./yaml/parameters_bump_loc.yml
fi
