#!/bin/ksh
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_HOFX
# Run SOCA HOFX
#================================================================================
#================================================================================
EOF

echo ''
echo 'Date of Analysis: ' $CDATE
echo 'Run Directory: ' $RUNCDATE
echo ''

cd $RUNCDATOOT_GODAS_DIR/ush/load_godas_modules.sh
status=$?
[[ $status -ne 0 ]] && exit $status

# Run H(x)
srun -n $NPE ${SOCA_EXEC}/soca_hofx3d.x ./yaml/hofx3d.yml

