#!/bin/bash
set -e

#================================================================================
#================================================================================
# 

echo ''
echo 'Running the JJOB for PREP_LETKF, aka SOCA HoFx'
echo 'Date of Analysis: ' $CDATE
echo 'Run Directory: ' $RUNCDATE
echo ''

module purge
source $MOD_PATH/godas.main
module list

rename_func () { for files in $1; do cp $files ${files:0:(${#files}-28)}'nc'; done }

# Rename the ensemble members
cd $RUNCDATE/Data

#find -type l -delete
# TODO Remove softlinks to pertubations before proceed, when the ensemble is in.
rename_func "cic.pert.ens.*.PT0S.nc"
rename_func "ocn.pert.ens.*.PT0S.nc"

cd $RUNCDATE

# Change of the coordinates
# TODO

# Get ENSBEG/ENSEND from ENSGRP and NMEM_EFCSGRP
export ENSEND=$((NMEM_PGRP * ENSGRP))
export ENSBEG=$((ENSEND - NMEM_PGRP + 1))

for MEMBER_NO in $(seq $ENSBEG $ENSEND); do
        echo $MEMBER_NO
        # Run H(x)
        srun -n $NPE ${SOCA_EXEC}/soca_hofx3d.x ./yaml/hofx3d$MEMBER_NO.yml
done
