databases:
  local:
    class: LocalDB
    root: /work/noaa/marine/Guillaume.Vernieres/OBS/r2d2test/
    cache_fetch: no

  shared:
    class: LocalDB
    root: /work/noaa/marine/marineda/r2d2/obs/
    cache_fetch: no

  archive: # name known by the end-user
    class: S3DB # which class to instantiate
    bucket: archive.jcsda
    cache_fetch: true

fetch_order:
  - local

store_order:
  - shared
  - local
  - archive
